version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.data:/app/.data
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    command: ["npm", "start"]
